-- MySQL Script generated by MySQL Workbench
-- Wed Jul 10 16:01:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sysinventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sysinventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sysinventario` DEFAULT CHARACTER SET utf8 ;
USE `sysinventario` ;

-- -----------------------------------------------------
-- Table `sysinventario`.`colores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`colores` (
  `idcolor` INT NOT NULL AUTO_INCREMENT,
  `colorheader` VARCHAR(45) NULL,
  `colormenu` VARCHAR(45) NULL,
  `colorhover` VARCHAR(45) NULL,
  `colorhovertext` VARCHAR(45) NULL,
  `colorpanel` VARCHAR(45) NULL,
  PRIMARY KEY (`idcolor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`temas` (
  `idtema` INT NOT NULL AUTO_INCREMENT,
  `nombretema` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  `idcolor` INT NULL,
  PRIMARY KEY (`idtema`),
  INDEX `fk_color_tema_idx` (`idcolor` ASC),
  CONSTRAINT `fk_color_tema`
    FOREIGN KEY (`idcolor`)
    REFERENCES `sysinventario`.`colores` (`idcolor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`configuracion` (
  `idconfiguracion` INT NOT NULL AUTO_INCREMENT,
  `moneda` VARCHAR(45) NULL,
  `simbolo` VARCHAR(5) NULL,
  `nombresistema` VARCHAR(45) NULL,
  `idtema` INT NULL,
  PRIMARY KEY (`idconfiguracion`),
  INDEX `fktema_conf_idx` (`idtema` ASC),
  CONSTRAINT `fktema_conf`
    FOREIGN KEY (`idtema`)
    REFERENCES `sysinventario`.`temas` (`idtema`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`documentos` (
  `iddocumento` INT NOT NULL AUTO_INCREMENT,
  `tipo_documento` VARCHAR(45) NULL,
  `num_documento` VARCHAR(45) NULL,
  PRIMARY KEY (`iddocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`direcciones` (
  `iddireccion` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NULL,
  `dep/estado` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`iddireccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`info_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`info_empresa` (
  `idinfo_empresa` INT NOT NULL AUTO_INCREMENT,
  `tipoempresa` VARCHAR(45) NULL,
  `iddocumento` INT NULL,
  `nombreempresa` VARCHAR(45) NULL,
  `logo` VARCHAR(70) NULL,
  `iddireccion` INT NULL,
  `telefono` VARCHAR(15) NULL,
  `correo` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `obserbaciones` VARCHAR(45) NULL,
  `celular` VARCHAR(15) NULL,
  `saldoinicial` DOUBLE NULL,
  PRIMARY KEY (`idinfo_empresa`),
  INDEX `fk_info_document_idx` (`iddocumento` ASC),
  INDEX `fk_info_direccion_idx` (`iddireccion` ASC),
  CONSTRAINT `fk_info_document`
    FOREIGN KEY (`iddocumento`)
    REFERENCES `sysinventario`.`documentos` (`iddocumento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_info_direccion`
    FOREIGN KEY (`iddireccion`)
    REFERENCES `sysinventario`.`direcciones` (`iddireccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`personas` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `tipopersona` VARCHAR(45) NULL,
  `iddocumento` INT NULL,
  `nombre` VARCHAR(60) NULL,
  `telefono` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `iddireccion` INT NULL,
  PRIMARY KEY (`idpersona`),
  INDEX `fk_persona_documento_idx` (`iddocumento` ASC),
  INDEX `fk_persona_direccion_idx` (`iddireccion` ASC),
  CONSTRAINT `fk_persona_documento`
    FOREIGN KEY (`iddocumento`)
    REFERENCES `sysinventario`.`documentos` (`iddocumento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_persona_direccion`
    FOREIGN KEY (`iddireccion`)
    REFERENCES `sysinventario`.`direcciones` (`iddireccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`clientes` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `idpersona` INT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_persona_cliente_idx` (`idpersona` ASC),
  CONSTRAINT `fk_persona_cliente`
    FOREIGN KEY (`idpersona`)
    REFERENCES `sysinventario`.`personas` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`empleados` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `idpersona` INT NULL,
  `salario` DOUBLE NULL,
  PRIMARY KEY (`idempleado`),
  INDEX `fk_empleado_persona_idx` (`idpersona` ASC),
  CONSTRAINT `fk_empleado_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `sysinventario`.`personas` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`proveedores` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `idpersona` INT NULL,
  PRIMARY KEY (`idproveedor`),
  INDEX `fk_persona_idx` (`idpersona` ASC),
  CONSTRAINT `fk_persona_proveedor`
    FOREIGN KEY (`idpersona`)
    REFERENCES `sysinventario`.`personas` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idempleado` INT NULL,
  `usuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_emp_usuario_idx` (`idempleado` ASC),
  CONSTRAINT `fk_emp_usuario`
    FOREIGN KEY (`idempleado`)
    REFERENCES `sysinventario`.`empleados` (`idempleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`departamentos` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `idempleado` INT NULL,
  `nombredepartamento` VARCHAR(45) NULL,
  PRIMARY KEY (`iddepartamento`),
  INDEX `fk_dep_emp_idx` (`idempleado` ASC),
  CONSTRAINT `fk_dep_emp`
    FOREIGN KEY (`idempleado`)
    REFERENCES `sysinventario`.`empleados` (`idempleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`categorias` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `categorias` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`productos` (
  `idproducto` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `idcategoria` INT NULL,
  `unidadmedida` VARCHAR(45) NULL,
  `cantidad` DOUBLE NULL,
  `costounitario` DOUBLE NULL,
  `precioventa` DOUBLE NULL,
  `existencias` DOUBLE NULL DEFAULT 0,
  `stockseguridad` DOUBLE NULL DEFAULT 5,
  `foto` VARCHAR(100) NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_categoria_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `sysinventario`.`categorias` (`idcategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`compras` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `idproveedor` INT NULL,
  `importetotal` DOUBLE NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_importe_proveedor_idx` (`idproveedor` ASC),
  CONSTRAINT `fk_importe_proveedor`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `sysinventario`.`proveedores` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`detalle_compra` (
  `iddetalle_compra` INT NOT NULL AUTO_INCREMENT,
  `idcompra` INT NULL,
  `idproducto` INT NULL,
  `cantidad` DOUBLE NULL,
  `descuento` DOUBLE NULL,
  `importe` DOUBLE NULL,
  PRIMARY KEY (`iddetalle_compra`),
  INDEX `fk_detalle_c_producto_idx` (`idproducto` ASC),
  INDEX `fk_compra_detalle_idx` (`idcompra` ASC),
  CONSTRAINT `fk_detalle_c_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `sysinventario`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_detalle`
    FOREIGN KEY (`idcompra`)
    REFERENCES `sysinventario`.`compras` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`ventas` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NULL,
  `importetotal` DOUBLE NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idventa`),
  INDEX `fk_ventas_cliente_idx` (`idcliente` ASC),
  CONSTRAINT `fk_ventas_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `sysinventario`.`clientes` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`detalleventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`detalleventas` (
  `iddetalleventa` INT NOT NULL AUTO_INCREMENT,
  `idventa` INT NULL,
  `idproducto` INT NULL,
  `cantidad` DOUBLE NULL,
  `descuento` DOUBLE NULL,
  `importe` DOUBLE NULL,
  PRIMARY KEY (`iddetalleventa`),
  INDEX `fk_ventas_detallee_idx` (`idventa` ASC),
  INDEX `fk_detalleee_producto_idx` (`idproducto` ASC),
  CONSTRAINT `fk_ventas_detallee`
    FOREIGN KEY (`idventa`)
    REFERENCES `sysinventario`.`ventas` (`idventa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalleee_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `sysinventario`.`productos` (`idproducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`devolucionescompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`devolucionescompra` (
  `iddevolucionescompra` INT NOT NULL AUTO_INCREMENT,
  `idcompra` INT NULL,
  `idproveedor` INT NULL,
  `importetotal` DOUBLE NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`iddevolucionescompra`),
  INDEX `fk_compra_devoluciones_idx` (`idcompra` ASC),
  INDEX `fk_dev_compra_proveedor_idx` (`idproveedor` ASC),
  CONSTRAINT `fk_compra_devoluciones`
    FOREIGN KEY (`idcompra`)
    REFERENCES `sysinventario`.`compras` (`idcompra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dev_compra_proveedor`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `sysinventario`.`proveedores` (`idproveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`detalledevolucionescompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`detalledevolucionescompra` (
  `iddetalledevolucionescompra` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NULL,
  `cantidad` DOUBLE NULL,
  `importe` DOUBLE NULL,
  `iddevoluciones` INT NULL,
  PRIMARY KEY (`iddetalledevolucionescompra`),
  INDEX `fk_devolucones_detallee_idx` (`iddevoluciones` ASC),
  INDEX `fk_devoluciones_prod_idx` (`idproducto` ASC),
  CONSTRAINT `fk_devolucones_detallee`
    FOREIGN KEY (`iddevoluciones`)
    REFERENCES `sysinventario`.`devolucionescompra` (`iddevolucionescompra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_devoluciones_prod`
    FOREIGN KEY (`idproducto`)
    REFERENCES `sysinventario`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`devolucionesventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`devolucionesventa` (
  `iddevolucionventa` INT NOT NULL AUTO_INCREMENT,
  `idventa` INT NULL,
  `idcliente` INT NULL,
  `importetotal` DOUBLE NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`iddevolucionventa`),
  INDEX `fk_devventa_venta_idx` (`idventa` ASC),
  INDEX `fk_devventa_cliente_idx` (`idcliente` ASC),
  CONSTRAINT `fk_devventa_venta`
    FOREIGN KEY (`idventa`)
    REFERENCES `sysinventario`.`ventas` (`idventa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_devventa_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `sysinventario`.`ventas` (`idventa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`detalledevolucionesventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`detalledevolucionesventa` (
  `iddetalledevolucionventa` INT NOT NULL AUTO_INCREMENT,
  `iddevolucionventa` INT NULL,
  `idproducto` INT NULL,
  `cantidad` DOUBLE NULL,
  `importe` DOUBLE NULL,
  PRIMARY KEY (`iddetalledevolucionventa`),
  INDEX `fk_producuto_det_dev_venta_idx` (`idproducto` ASC),
  INDEX `fk_dev_venta_detalle_dev_venta_idx` (`iddevolucionventa` ASC),
  CONSTRAINT `fk_producuto_det_dev_venta`
    FOREIGN KEY (`idproducto`)
    REFERENCES `sysinventario`.`productos` (`idproducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dev_venta_detalle_dev_venta`
    FOREIGN KEY (`iddevolucionventa`)
    REFERENCES `sysinventario`.`devolucionesventa` (`iddevolucionventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`entradasdinero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`entradasdinero` (
  `idcortediario` INT NOT NULL AUTO_INCREMENT,
  `entradas` DECIMAL(10,2) NULL,
  `salidas` DECIMAL(10,2) NULL,
  `capital` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idcortediario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysinventario`.`pagoempleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysinventario`.`pagoempleados` (
  `idpagoempleado` INT NOT NULL AUTO_INCREMENT,
  `total` DOUBLE NULL DEFAULT 0,
  PRIMARY KEY (`idpagoempleado`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
