package com.devs.entities;
// Generated sep 12, 2019 10:05:33 a.m. by Hibernate Tools 4.3.1



/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private Integer idarea;
     private Gerencia gerencia;
     private String nombre;
     private Puestos puestos;

    public Area() {
    }

    public Area(Gerencia gerencia, String nombre, Puestos puestos) {
       this.gerencia = gerencia;
       this.nombre = nombre;
       this.puestos = puestos;
    }
   
    public Integer getIdarea() {
        return this.idarea;
    }
    
    public void setIdarea(Integer idarea) {
        this.idarea = idarea;
    }
    public Gerencia getGerencia() {
        return this.gerencia;
    }
    
    public void setGerencia(Gerencia gerencia) {
        this.gerencia = gerencia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Puestos getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Puestos puestos) {
        this.puestos = puestos;
    }
@Override
public String toString(){
    return nombre.toString();
}



}


