package com.devs.entities;
// Generated sep 12, 2019 10:05:33 a.m. by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private Integer idcontrato;
     private Empleados empleados;
     private Date fechainicio;
     private Date finalizacion;
     private String extendido;
     private String lugartrabajo;
     private Set devengoses = new HashSet(0);
     private Set obligacioneses = new HashSet(0);

    public Contrato() {
    }

    public Contrato(Empleados empleados, Date fechainicio, Date finalizacion, String extendido, String lugartrabajo, Set devengoses, Set obligacioneses) {
       this.empleados = empleados;
       this.fechainicio = fechainicio;
       this.finalizacion = finalizacion;
       this.extendido = extendido;
       this.lugartrabajo = lugartrabajo;
       this.devengoses = devengoses;
       this.obligacioneses = obligacioneses;
    }
   
    public Integer getIdcontrato() {
        return this.idcontrato;
    }
    
    public void setIdcontrato(Integer idcontrato) {
        this.idcontrato = idcontrato;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFinalizacion() {
        return this.finalizacion;
    }
    
    public void setFinalizacion(Date finalizacion) {
        this.finalizacion = finalizacion;
    }
    public String getExtendido() {
        return this.extendido;
    }
    
    public void setExtendido(String extendido) {
        this.extendido = extendido;
    }
    public String getLugartrabajo() {
        return this.lugartrabajo;
    }
    
    public void setLugartrabajo(String lugartrabajo) {
        this.lugartrabajo = lugartrabajo;
    }
    public Set getDevengoses() {
        return this.devengoses;
    }
    
    public void setDevengoses(Set devengoses) {
        this.devengoses = devengoses;
    }
    public Set getObligacioneses() {
        return this.obligacioneses;
    }
    
    public void setObligacioneses(Set obligacioneses) {
        this.obligacioneses = obligacioneses;
    }




}


