package com.devs.entities;
// Generated sep 12, 2019 10:05:33 a.m. by Hibernate Tools 4.3.1



/**
 * Devengos generated by hbm2java
 */
public class Devengos  implements java.io.Serializable {


     private Integer iddevengo;
     private Contrato contrato;
     private String descripcion;

    public Devengos() {
    }

    public Devengos(Contrato contrato, String descripcion) {
       this.contrato = contrato;
       this.descripcion = descripcion;
    }
   
    public Integer getIddevengo() {
        return this.iddevengo;
    }
    
    public void setIddevengo(Integer iddevengo) {
        this.iddevengo = iddevengo;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


