package com.devs.entities;
// Generated sep 12, 2019 10:05:33 a.m. by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gerencia generated by hbm2java
 */
public class Gerencia  implements java.io.Serializable {


     private Integer idgerencia;
     private String nombre;
     private String telefono;
     private Set areas = new HashSet(0);
     private Set usuarioses = new HashSet(0);

    public Gerencia() {
    }

    public Gerencia(String nombre, String telefono, Set areas, Set usuarioses) {
       this.nombre = nombre;
       this.telefono = telefono;
       this.areas = areas;
       this.usuarioses = usuarioses;
    }
   
    public Integer getIdgerencia() {
        return this.idgerencia;
    }
    
    public void setIdgerencia(Integer idgerencia) {
        this.idgerencia = idgerencia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getAreas() {
        return this.areas;
    }
    
    public void setAreas(Set areas) {
        this.areas = areas;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }
    


@Override
public String toString(){
    return nombre.toString();
}

}


