package com.devs.entities;
// Generated sep 12, 2019 10:05:33 a.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Pagomensual generated by hbm2java
 */
public class Pagomensual  implements java.io.Serializable {


     private Integer idpagomensual;
     private Empleados empleados;
     private Planillas planillas;
     private BigDecimal isss;
     private BigDecimal afp;
     private BigDecimal salarionetomensual;

    public Pagomensual() {
    }

    public Pagomensual(Empleados empleados, Planillas planillas, BigDecimal isss, BigDecimal afp, BigDecimal salarionetomensual) {
       this.empleados = empleados;
       this.planillas = planillas;
       this.isss = isss;
       this.afp = afp;
       this.salarionetomensual = salarionetomensual;
    }
   
    public Integer getIdpagomensual() {
        return this.idpagomensual;
    }
    
    public void setIdpagomensual(Integer idpagomensual) {
        this.idpagomensual = idpagomensual;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public Planillas getPlanillas() {
        return this.planillas;
    }
    
    public void setPlanillas(Planillas planillas) {
        this.planillas = planillas;
    }
    public BigDecimal getIsss() {
        return this.isss;
    }
    
    public void setIsss(BigDecimal isss) {
        this.isss = isss;
    }
    public BigDecimal getAfp() {
        return this.afp;
    }
    
    public void setAfp(BigDecimal afp) {
        this.afp = afp;
    }
    public BigDecimal getSalarionetomensual() {
        return this.salarionetomensual;
    }
    
    public void setSalarionetomensual(BigDecimal salarionetomensual) {
        this.salarionetomensual = salarionetomensual;
    }




}


