package com.devs.entities;
// Generated sep 12, 2019 10:05:33 a.m. by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Planillas generated by hbm2java
 */
public class Planillas  implements java.io.Serializable {


     private Integer idplanilla;
     private Date desdeFecha;
     private Date hastaFecha;
     private Set pagomensuals = new HashSet(0);

    public Planillas() {
    }

    public Planillas(Date desdeFecha, Date hastaFecha, Set pagomensuals) {
       this.desdeFecha = desdeFecha;
       this.hastaFecha = hastaFecha;
       this.pagomensuals = pagomensuals;
    }
   
    public Integer getIdplanilla() {
        return this.idplanilla;
    }
    
    public void setIdplanilla(Integer idplanilla) {
        this.idplanilla = idplanilla;
    }
    public Date getDesdeFecha() {
        return this.desdeFecha;
    }
    
    public void setDesdeFecha(Date desdeFecha) {
        this.desdeFecha = desdeFecha;
    }
    public Date getHastaFecha() {
        return this.hastaFecha;
    }
    
    public void setHastaFecha(Date hastaFecha) {
        this.hastaFecha = hastaFecha;
    }
    public Set getPagomensuals() {
        return this.pagomensuals;
    }
    
    public void setPagomensuals(Set pagomensuals) {
        this.pagomensuals = pagomensuals;
    }




}


