package com.devs.entities;
// Generated sep 12, 2019 10:05:33 a.m. by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idusuario;
     private Gerencia gerencia;
     private String usuario;
     private String password;

    public Usuarios() {
    }

    public Usuarios(Gerencia gerencia, String usuario, String password) {
       this.gerencia = gerencia;
       this.usuario = usuario;
       this.password = password;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public Gerencia getGerencia() {
        return this.gerencia;
    }
    
    public void setGerencia(Gerencia gerencia) {
        this.gerencia = gerencia;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


